### ISSUE TITLE
execute the code "go run main.go" error

### ISSUE THREAD

**Issue by ryderkun** [theplant/device_management#1]
as follow:
go run main.go
# command-line-arguments

./main.go:252: cannot use warehouse.EditAttrs() (type []_admin.Section) as type []interface {} in argument to warehouse.NewAttrs
./main.go:259: cannot use warehouse.EditAttrs() (type []_admin.Section) as type []interface {} in argument to deviceCheckCompany.NewAttrs

**Comment by binku87** [comment]
Hi ryderkun

Please update the repo. This patch (https://github.com/theplant/device_management/commit/dd686b27e52531b8d52d8d2874c93864e4942093) will fix this error.
